# Generated by Django 4.0.4 on 2022-07-29 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdate', models.DateField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField(auto_now_add=True)),
                ('positive', models.IntegerField(default=0)),
                ('negative', models.IntegerField(default=0)),
                ('neutral', models.IntegerField(default=0)),
                ('sentiment', models.CharField(blank=True, max_length=50)),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Responsemaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsedate', models.DateField(auto_now_add=True)),
                ('level', models.CharField(default='', max_length=100)),
                ('bookingid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='Responsechild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('response', models.CharField(max_length=50)),
                ('respid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_app.responsemaster')),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=500)),
                ('surveyid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_app.survey')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='regid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_app.registration'),
        ),
        migrations.AddField(
            model_name='booking',
            name='therapistid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mental_app.therapist'),
        ),
    ]
